export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
export { default as Profile } from './Profile' 
export { default as Admission } from '../pages/Admission/Admission'
export { default as Research } from '../pages/Research/Research'
export { default as Community} from '../pages/Community/Community'
export { default as EditPost } from './Community/EditPost'
export { default as BookmarkBoard } from './Community/BookmarkBoard'